apiVersion: v1
appVersion: "latest"
description: Complete deployment of Patavi cluster environment
name: patavi
version: 0.0.1
icon: https://raw.githubusercontent.com/drugis/addis-core/master/src/main/webapp/resources/public/img/favicon.ico
maintainers:
  - name: sidohaakma
  - name: chinook25
