apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ template "survey.fullname" . }}
  labels:
    app: {{ template "survey.name" . }}
    chart: {{ template "survey.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  api-key: {{ .Values.patavi.apiKey | b64enc | quote }}
  cookie-secret: {{ .Values.mcda.cookieSecret | b64enc | quote }}
  database-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
