image:
  repository: registry.drugis.org/mcda-survey
  pullPolicy: IfNotPresent
  tag: "k8s"

mcda:
  cookieDomain: dev.molgenis.org
  host: http://enterprise-mcda
  existingSecret: secret-enterprise-mcda

patavi:
  port: 3000
  host: patavi-patavi-server.patavi.svc

postgresql:
  postgresqlHost: enterprise-mcda-postgresql
  postgresqlUsername: mcda
  postgresqlDatabase: mcda
  existingSecret: enterprise-mcda-postgresql

service:
  type: ClusterIP
  port: 3003

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: survey.dev.molgenis.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

replicaCount: 1
imagePullSecrets:
  - name: drugis
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
