addis-core:
  postgresql:
    postgresqlPassword: xxxx
  image:
    repository: addis/addis
    tag: "test-20211203"
  addis:
    googleKey: xxxx
    googleSecret: xxxx
    importer: http://nct-import.nct-import.svc
  jena:
    apiKey: xxxx
    uriPrefix: https://jena.dev.molgenis.org
    baseUri: http://addis-jena-es.addis.svc
  patavi:
    apiKey: xxxx
    host: http://patavi.patavi-patavi-server.svc:3000
  ingress:
    enabled: true
    hosts:
      - host: addis.drugis.org
        paths:
          - path: /
            pathType: ImplementationSpecific

jena-es:
  image:
    repository: addis/jena-es
    tag: "test"
  jena:
    apiKey: xxxx
    eventSourceUriPrefix: https://jena.dev.molgenis.org

nct-import:
  image:
    repository: addis/nct-import
    tag: "latest"
