
{{ if not .Values.rabbitmq.secretNameOverride -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patavi-worker.fullname" . }}
  labels:
{{ include "patavi-worker.labels" . | indent 4 }}
type: Opaque
data:
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote }}
{{- end }}