{{ if .Values.mcda.enterprise.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: secret-enterprise-init-{{ template "mcda.fullname" . }}
  labels:
    app: {{ template "mcda.name" . }}
    chart: {{ template "mcda.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
stringData:
  create_user.sql: |
    INSERT INTO Account (username, firstName, lastName, password) SELECT 'administrator', 'admin', '', '\\$2a\\$10\\$TmvbK5.HpkoPGDV5ykycsOFIJbvDHAtgwW.JfyLNGPrBCSABAq9Na' WHERE NOT EXISTS (SELECT * FROM account WHERE username = 'administrator');
    INSERT INTO administrator (accountid) (SELECT id FROM account WHERE username='administrator');
{{ end -}}


