apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ template "patavi.fullname" . }}
  labels:
    app: {{ template "patavi.name" . }}
    chart: {{ template "patavi.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  api-key: {{ .Values.apiKey | b64enc | quote }}