replicaCount: 1

image:
  repository: addis/patavi
  pullPolicy: IfNotPresent
  tag: "secure6"

postgresql:
  postgresqlUsername: patavi
  postgresqlDatabase: patavi
  postgresqlPassword: xxxxx

hostLink: patavi.dev.molgenis.org
proxyHost: patavi.dev.molgenis.org
apiKey: xxxxx

rabbit:
  host: rabbitmq.rabbitmq.svc
  user: drugis
  password: verysecret

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: patavi.drugis.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
