apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "gemtc.fullname" . }}-postgres-backup
spec:
  schedule: "{{ .Values.backup.cron }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup
              image: postgres:11
              command: ["/bin/sh"]
              args: ["-c", 'PGPASSWORD="$(POSTGRES_PASSWORD)" pg_dump -U {{ .Values.postgresql.postgresqlUsername }} -h {{ include "call-nested" (list $ "postgresql" "postgresql.fullname") }} {{ .Values.postgresql.postgresqlDatabase }} > /var/backups/backup-$(date +"%m-%d-%Y-%H-%M").sql']
              volumeMounts:
                - name: postgres-backup
                  mountPath: /var/backups
              env: 
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "call-nested" (list $ "postgresql" "postgresql.fullname") }}
                      key: postgresql-password
          restartPolicy: Never
          volumes:
            - name: postgres-backup
              persistentVolumeClaim:
                claimName: {{ include "gemtc.fullname" . }}-backup
