apiVersion: v1
name: gemtc
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: "0.10.4"
icon: https://github.com/drugis/gemtc/raw/master/server/public/img/favicon.png
maintainers:
- name: chinook25
- name: sidohaakma
