replicaCount: 1

image:
  repository: addis/gemtc
  pullPolicy: IfNotPresent
  tag: "test"

patavi:
  apiKey: xxxxx
  host: patavi-patavi-server.patavi.svc
  port: 3000

postgresql:
  postgresqlUsername: gemtc
  postgresqlDatabase: gemtc
  postgresqlPassword: xxxxx
  persistence:
    useExistingClaim: false
  #   existingClaim: data-patavi-server-postgresql-0
    storageClass: nfs-provisioner-retain
  image: 
    debug: false

gemtc:
  googleKey: xxxx
  googleSecret: xxxx
  cookieSecret: xxxx
  host: https://gemtc.dev.molgenis.org
  secure: "false"
  authenticationMethod: GOOGLE
  schema:
    version: develop
  enterprise:
    enabled: false
    # adminPassword: xxxx

backup:
  enabled: true
  cron: "0 2 * * *"
  persistence:
    enabled: true
    storageClass: "nfs-provisioner-retain"
    accessMode: ReadWriteOnce
    size: 5Gi
    useExistingClaim: false
    # existingClaim: gemtc-backup

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3001

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: gemtc.dev.molgenis.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
